version: "3.9"

services:
  mysql:
    image: mysql
    container_name: trustcare-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: trustcare
      MYSQL_USER: ruchi
      MYSQL_PASSWORD: ruchi
    ports:
      - "5432:5432"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
